# Site settings
title: ZhouSh Blog
SEOTitle: 周诗蕙的博客 | ZhouSh Blog
header-img: img/bg-guidao10.jpg
email: zhoushihui210@foxmail.com
description: "这里是周诗蕙的个人博客"
#keyword: ""
url: "https://zhoush210.github.io/" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username: huxpro
#zhihu_username: huxpro
github_username: ZhouShihui210
bilibili_uid: 291406031 # 你主页的链接
#twitter_username: huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
#disqus_username: hux

# Netease settings
#netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: ""
sidebar-avatar: /img/profile.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
#chrome-tab-theme-color: "#000000"
#service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true

# Friends
# { title: "羟基香豆素", href: "https://hydroxycoumarin.github.io/" },
friends:
  [
    { title: "无处不在的小土", href: "https://gaoyichao.com/Xiaotu/" },
    { title: "沉默杀手", href: "https://charon-cheung.github.io" },
    { title: "膜法师猫定谔", href: "http://www.fangmuseum.com" },
    { title: "qbb", href: "https://www.qbb.sh/" },
    { title: "linyang", href: "http://www.yangjlin.com" },
    { title: "linyang's phtography", href: "http://yanglin.photo" }
  ]
